root: true
env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - airbnb
  - airbnb-typescript
  - airbnb/hooks
  - plugin:prettier/recommended
ignorePatterns:
  - dist/**/*
  - build/**/*
  - node_modules/**/*
  - vite.config.ts
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
rules:
  no-console: warn
  react/react-in-jsx-scope: off
  react/no-unknown-property: off
  '@typescript-eslint/no-unused-vars': warn
